"use server";

/* ============================================================
 * Curricula CRUD — admin-only. Classes reference a curriculum via
 * classes.curriculum_id (NOT NULL).
 * ============================================================ */

import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { getDb } from "@/lib/db";
import { requireAdmin } from "@/lib/dal";

export interface ActionResult {
  ok: boolean;
  error?: string;
}

export interface CreateCurriculumInput {
  title: string;
  description?: string;
  ageRange?: string;
}

export async function createCurriculum(input: CreateCurriculumInput): Promise<ActionResult & { id?: string }> {
  await requireAdmin();
  const title = (input.title ?? "").trim();
  if (!title) return { ok: false, error: "Title is required." };
  if (title.length > 200) return { ok: false, error: "Title is too long." };
  const description = (input.description ?? "").trim().slice(0, 2000);
  const ageRange = (input.ageRange ?? "").trim().slice(0, 60);

  const id = `pfx-${randomUUID().slice(0, 8)}`;
  const now = Date.now();
  (await getDb()
        .prepare(
          "INSERT INTO curricula (id, title, description, age_range, published, created_at, updated_at) VALUES (?, ?, ?, ?, 1, ?, ?)",
        )
        .run(id, title.slice(0, 200), description || null, ageRange || null, now, now));

  revalidatePath("/app/curriculum");
  return { ok: true, id };
}

export interface UpdateCurriculumPatch {
  title?: string;
  description?: string;
  ageRange?: string;
  published?: boolean;
}

export async function updateCurriculum(id: string, patch: UpdateCurriculumPatch): Promise<ActionResult> {
  await requireAdmin();
  const db = getDb();
  const row = (await db.prepare("SELECT * FROM curricula WHERE id = ?").get(id)) as { id: string } | undefined;
  if (!row) return { ok: false, error: "Not found." };

  const sets: string[] = [];
  const vals: unknown[] = [];
  if (patch.title !== undefined) {
    const title = patch.title.trim();
    if (!title) return { ok: false, error: "Title can't be empty." };
    sets.push("title = ?");
    vals.push(title.slice(0, 200));
  }
  if (patch.description !== undefined) {
    sets.push("description = ?");
    vals.push(patch.description.trim().slice(0, 2000) || null);
  }
  if (patch.ageRange !== undefined) {
    sets.push("age_range = ?");
    vals.push(patch.ageRange.trim().slice(0, 60) || null);
  }
  if (patch.published !== undefined) {
    sets.push("published = ?");
    vals.push(patch.published ? 1 : 0);
  }
  if (sets.length === 0) return { ok: true };

  sets.push("updated_at = ?");
  vals.push(Date.now());
  vals.push(id);
  (await db.prepare(`UPDATE curricula SET ${sets.join(", ")} WHERE id = ?`).run(...(vals as [])));

  revalidatePath("/app/curriculum");
  revalidatePath(`/app/curriculum/${id}`);
  return { ok: true };
}

/* ===================================================================== */

/**
 * Point a course at the authored track that holds its lessons — or unpoint it.
 *
 * This is deliberately a person's explicit choice from a list of real tracks,
 * never a title match. `curricula` (what staff schedule) and `learn_tracks`
 * (what authors write) are two graphs, and the only automatic link in the
 * system is the one migration 027 makes, where both ids are the same track
 * number generated by code in this repo.
 *
 * A track may back only one course. Two courses claiming the same lessons
 * would make "lesson 3 of this course" ambiguous the moment either one is
 * scheduled, and the composer maps sessions onto that sequence.
 */
export async function linkCourseToTrack(
  curriculumIdValue: string,
  learnTrackIdValue: string | null,
): Promise<ActionResult> {
  await requireAdmin();
  const curriculumId = (curriculumIdValue ?? "").trim().slice(0, 100);
  const learnTrackId = (learnTrackIdValue ?? "").trim().slice(0, 100) || null;
  if (!curriculumId) return { ok: false, error: "Choose a course." };

  const db = getDb();
  const course = await db.prepare("SELECT id FROM curricula WHERE id = ?").get(curriculumId);
  if (!course) return { ok: false, error: "That course no longer exists." };

  if (learnTrackId) {
    const track = await db.prepare("SELECT id FROM learn_tracks WHERE id = ?").get(learnTrackId);
    if (!track) return { ok: false, error: "That set of lessons no longer exists." };
    const claimed = (await db
      .prepare("SELECT title FROM curricula WHERE learn_track_id = ? AND id <> ?")
      .get(learnTrackId, curriculumId)) as { title: string } | undefined;
    if (claimed) {
      return { ok: false, error: `Those lessons already belong to “${claimed.title}”. Unlink it there first.` };
    }
  }

  await db
    .prepare("UPDATE curricula SET learn_track_id = ?, updated_at = ? WHERE id = ?")
    .run(learnTrackId, Date.now(), curriculumId);

  revalidatePath("/app/curriculum");
  revalidatePath(`/app/curriculum/${curriculumId}`);
  revalidatePath("/app/post-class");
  return { ok: true };
}
