import Link from "next/link";
import { Badge, Button } from "@/components/ds";
import { requireStaff } from "@/lib/dal";
import { getHiringCommandData } from "@/lib/people-work";
import HiringPackageForm from "@/components/app/hiring/HiringPackageForm";
import PublishOpeningButton from "@/components/app/hiring/PublishOpeningButton";

const VIEWS = ["attention", "candidates", "openings", "needs", "roles", "processes"] as const;
type View = typeof VIEWS[number];

export default async function HiringPage({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  const me = await requireStaff();
  const { view: requested } = await searchParams;
  const view: View = VIEWS.includes(requested as View) ? requested as View : "attention";
  const data = await getHiringCommandData();
  const labels: Record<View, string> = { attention: "Needs Attention", candidates: "Candidates", openings: "Openings", needs: "Hiring Needs", roles: "Roles", processes: "Processes" };
  return <main className="ops-page">
    <header className="ops-hero"><div className="ops-hero__copy"><span className="ops-eyebrow">BOW OS · Talent</span><h1 className="ops-title">Hiring</h1><p className="ops-summary">Every active candidate has an owner, a next action, and an immutable record of the process they entered.</p></div>{me.role === "admin" && <div className="ops-actions"><HiringPackageForm /></div>}</header>
    <nav className="ops-filters" aria-label="Hiring views">{VIEWS.map((item) => <Link key={item} className="ops-filter" aria-current={view === item ? "page" : undefined} href={item === "attention" ? "/app/hiring" : `/app/hiring?view=${item}`}>{labels[item]}</Link>)}</nav>
    {view === "attention" && <section className="ops-stack"><div><span className="ops-label">Default command view</span><h2 className="ops-section-title">What needs attention?</h2></div>{data.attention.length === 0 ? <div className="ops-empty"><Badge status="positive">Pipeline clear</Badge><h3 className="ops-empty__title" style={{ marginTop: 10 }}>No candidate is overdue or in limbo.</h3></div> : <div className="ops-list">{data.attention.map((item) => <article key={item.id} className="ops-list-row"><div><Link className="ops-record-name" href={`/app/hiring/applications/${item.id}`}>{item.personName}</Link><span className="ops-record-meta">{item.openingTitle} · {item.stageTitle}</span></div><div><span className="ops-label">Shown because</span><span className="ops-value">{item.reason}</span></div><div><span className="ops-label">Owner</span><span className="ops-value">{item.ownerName ?? "Unassigned"}</span></div><Badge status={item.tone}>{item.tone === "negative" ? "Act now" : item.tone === "warning" ? "Due soon" : "Next"}</Badge><Button href={`/app/hiring/applications/${item.id}`} size="sm" variant="secondary">Open</Button></article>)}</div>}</section>}
    {view === "candidates" && <section className="ops-panel ops-panel--flat"><div className="ops-section-head"><div><span className="ops-label">One canonical application list</span><h2 className="ops-section-title">Candidates</h2></div><Badge status="info">{data.candidates.length}</Badge></div><div className="ops-list">{data.candidates.map((candidate) => <article className="ops-list-row" key={candidate.id}><div><Link className="ops-record-name" href={`/app/hiring/applications/${candidate.id}`}>{candidate.personName}</Link><span className="ops-record-meta">{candidate.email}</span></div><div><span className="ops-label">Opening</span><span className="ops-value">{candidate.openingTitle}</span></div><div><span className="ops-label">Stage</span><span className="ops-value">{candidate.stageTitle}</span></div><div><span className="ops-label">Next</span><span className="ops-value">{candidate.nextAction ?? "Final"}</span></div><Badge status={["accepted"].includes(candidate.lifecycle) ? "positive" : ["rejected","withdrawn"].includes(candidate.lifecycle) ? "locked" : "info"}>{candidate.lifecycle}</Badge></article>)}</div></section>}
    {view === "needs" && <section className="ops-stack">{data.requisitions.map((need) => <article className="ops-panel" key={need.id}><div className="ops-section-head"><div><span className="ops-label">Hiring need</span><h2 className="ops-section-title">{need.title}</h2></div><Badge status={need.filled >= need.target ? "positive" : "warning"}>{need.filled} / {need.target} filled</Badge></div><div className="ops-meta-grid"><div className="ops-meta"><span className="ops-label">Pipeline</span><span className="ops-value ops-value--large">{need.pipeline}</span></div><div className="ops-meta"><span className="ops-label">Needed by</span><span className="ops-value">{need.neededBy ?? "Not set"}</span></div><div className="ops-meta"><span className="ops-label">Hiring owner</span><span className="ops-value">{need.ownerName ?? "Unassigned"}</span></div></div></article>)}</section>}
    {view === "openings" && <section className="ops-panel"><div className="ops-list">{data.openings.map((opening) => <div className="ops-list-row" key={opening.id}><div><span className="ops-record-name">{opening.title}</span><span className="ops-record-meta">/join/{opening.slug} · version {opening.version}</span></div><Badge status={opening.status === "published" ? "positive" : "neutral"}>{opening.status}</Badge>{opening.status === "published" ? <Button href={`/join/${opening.slug}`} size="sm" variant="secondary">View Public Page</Button> : me.role === "admin" ? <PublishOpeningButton openingId={opening.id} /> : null}</div>)}</div></section>}
    {view === "roles" && <section className="ops-panel"><div className="ops-list">{data.roles.map((role) => <div className="ops-list-row" key={role.id}><div><span className="ops-record-name">{role.title}</span><span className="ops-record-meta">{role.unitName}</span></div><Badge status={role.status === "active" ? "positive" : "locked"}>{role.status}</Badge></div>)}</div></section>}
    {view === "processes" && <section className="ops-panel"><div className="ops-list">{data.processes.map((process) => <div className="ops-list-row" key={process.id}><div><span className="ops-record-name">{process.name}</span><span className="ops-record-meta">Latest version {process.latestVersion}</span></div><Badge status={process.status === "active" ? "positive" : "locked"}>{process.status}</Badge></div>)}</div></section>}
  </main>;
}
