import { notFound } from "next/navigation";
import { Badge } from "@/components/ds";
import { requireStaff } from "@/lib/dal";
import { getApplicationCockpit } from "@/lib/people-work";
import ApplicationCockpitActions from "@/components/app/hiring/ApplicationCockpitActions";
import RetryCandidateInvitation from "@/components/app/hiring/RetryCandidateInvitation";
import RetryCandidateCommunication from "@/components/app/hiring/RetryCandidateCommunication";

function label(value: unknown) { return String(value ?? "").replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function when(value: unknown) { const date = new Date(Number(value)); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString(); }

export default async function ApplicationCockpitPage({ params }: { params: Promise<{ id: string }> }) {
  await requireStaff();
  const { id } = await params;
  const detail = await getApplicationCockpit(id);
  if (!detail) notFound();
  const app = detail.application;
  return <main className="ops-page">
    <header className="ops-hero"><div className="ops-hero__copy"><span className="ops-eyebrow">Candidate cockpit · {String(app.opening_title)}</span><h1 className="ops-title">{String(app.name)}</h1><p className="ops-summary">One page for identity, stage, owner, next action, evidence, scheduling, communication, and decision.</p></div><Badge status={app.lifecycle_status === "accepted" ? "positive" : app.lifecycle_status === "rejected" ? "negative" : "info"}>{label(app.lifecycle_status)}</Badge></header>
    <div className="ops-two-col"><div className="ops-stack">
      <section className="ops-panel"><div className="ops-section-head"><div><span className="ops-label">Current state</span><h2 className="ops-section-title">{String(app.stage_title)}</h2></div><Badge status="info">Opening V{Number(app.opening_version)} · Process V{Number(app.process_version)}</Badge></div><div className="ops-meta-grid"><div className="ops-meta"><span className="ops-label">Owner</span><span className="ops-value">{String(app.owner_name ?? "Unassigned")}</span></div><div className="ops-meta"><span className="ops-label">Next action</span><span className="ops-value">{String(app.next_action ?? app.waiting_on ?? "Final")}</span></div><div className="ops-meta"><span className="ops-label">Next owner</span><span className="ops-value">{String(app.next_owner_name ?? "Unassigned")}</span></div><div className="ops-meta"><span className="ops-label">Source</span><span className="ops-value">{String(app.source ?? "Unknown")}</span></div></div></section>
      <section className="ops-panel"><div className="ops-section-head"><div><span className="ops-label">Configured evidence</span><h2 className="ops-section-title">Application</h2></div></div><div className="ops-meta-grid">{Object.entries(app.answers as Record<string,string>).map(([key, value]) => <div className="ops-meta" key={key}><span className="ops-label">{label(key)}</span><span className="ops-value">{value || "—"}</span></div>)}</div></section>
      <section className="ops-panel"><div className="ops-section-head"><div><span className="ops-label">Appointments</span><h2 className="ops-section-title">Interviews &amp; Mini-Teach</h2></div></div>{detail.interviews.length === 0 ? <p className="ops-body">No interview event created yet.</p> : <div className="ops-list">{detail.interviews.map((event) => <div className="ops-list-row" key={String(event.id)}><div><span className="ops-record-name">{String(event.stage_title)}</span><span className="ops-record-meta">{event.scheduled_at ? when(event.scheduled_at) : "Needs scheduling"} · {String(event.timezone ?? "")}</span></div><Badge status={event.status === "completed" ? "positive" : event.status === "no_show" ? "negative" : "warning"}>{label(event.status)}</Badge></div>)}</div>}</section>
      <section className="ops-panel"><div className="ops-section-head"><div><span className="ops-label">Structured human judgment</span><h2 className="ops-section-title">Evaluations</h2></div></div>{detail.evaluations.length === 0 ? <p className="ops-body">No scorecard submitted yet.</p> : <div className="ops-timeline">{detail.evaluations.map((evaluation) => <article className="ops-timeline__item" key={String(evaluation.id)}><span className="ops-record-name">{String(evaluation.scorecard_name)}</span><span className="ops-record-meta">{String(evaluation.evaluator_name)} · {when(evaluation.submitted_at)}</span><p className="ops-body" style={{ marginTop: 8 }}>{String(evaluation.evidence_note)}</p><Badge status={evaluation.recommendation === "strong_hire" || evaluation.recommendation === "hire" ? "positive" : evaluation.recommendation === "do_not_hire" ? "negative" : "warning"}>{label(evaluation.recommendation)}</Badge></article>)}</div>}</section>
      <ApplicationCockpitActions applicationId={id} revision={Number(app.revision)} currentStageId={String(app.current_stage_version_id)} lifecycle={String(app.lifecycle_status)} stages={detail.stages.map((stage) => ({ id: String(stage.id), title: String(stage.title), stage_type: String(stage.stage_type), ordinal: Number(stage.ordinal), scorecard_version_id: stage.scorecard_version_id ? String(stage.scorecard_version_id) : null }))} interviews={detail.interviews.map((event) => ({ id: String(event.id), stage_version_id: String(event.stage_version_id), status: String(event.status), revision: Number(event.revision) }))} />
    </div><aside className="ops-stack">
      <section className="ops-panel ops-panel--ink"><span className="ops-label" style={{ color: "#b9bcc4" }}>Canonical person</span><h2 className="ops-section-title" style={{ color: "#fff", marginTop: 8 }}>{String(app.name)}</h2><p className="ops-body" style={{ color: "#b9bcc4", marginTop: 10 }}>{String(app.email)}<br />{String(app.phone || "No phone recorded")}<br />Identity: {label(app.identity_status)}</p></section>
      <section className="ops-panel"><div className="ops-section-head"><div><span className="ops-label">Append-only history</span><h2 className="ops-section-title">Timeline</h2></div></div><div className="ops-timeline">{detail.events.map((event) => <div className="ops-timeline__item" key={String(event.id)}><span className="ops-record-meta">{when(event.created_at)} · {label(event.event_type)}</span><p className="ops-body" style={{ marginTop: 4 }}>{String(event.from_title ?? "Start")} → {String(event.to_title)}{event.note ? ` · ${String(event.note)}` : ""}</p></div>)}</div></section>
      <section className="ops-panel"><div className="ops-section-head"><div><span className="ops-label">Delivery state</span><h2 className="ops-section-title">Communications</h2></div></div>{detail.communications.length === 0 ? <p className="ops-body">No recorded communication yet.</p> : detail.communications.map((message) => <div className="ops-meta" key={String(message.id)}><span className="ops-value">{String(message.subject ?? message.channel)}</span><span className="ops-record-meta">{label(message.status)} · {when(message.created_at)}</span>{message.status === "failed" && !String(message.idempotency_key).startsWith("accepted-invitation:") && <RetryCandidateCommunication communicationId={String(message.id)} />}</div>)}{detail.communications.some((message) => message.status === "failed" && String(message.idempotency_key).startsWith("accepted-invitation:")) && app.lifecycle_status === "accepted" && <div style={{ marginTop: 12 }}><RetryCandidateInvitation applicationId={id} /></div>}</section>
    </aside></div>
  </main>;
}
